### ISSUE TITLE
Edit on Github in readthedocs links to a 404

### ISSUE THREAD

**Issue by mratsim** [quantumblacklabs/causalnex#3]
The edit on Github links to a non-existing https://github.com/quantumblacklabs/causalnex/blob/master/docs/index.rst file

![image](https://user-images.githubusercontent.com/22738317/73352862-565fd180-4292-11ea-821b-52de4284d81a.png)

Instead it should probably lead to the repo.

**Comment by tsanikgr** [comment]
Thank you very much @mratsim for reporting this. This was fixed in https://github.com/quantumblacklabs/causalnex/commit/ad047abf0f5b9ae7e11617ec214b8d3b6cb9c3aa so closing :)

**Comment by ryantsullivan** [comment]
It doesn't look like that commit fixed this; I am still getting the 404.

**Comment by tsanikgr** [comment]
We 'll have to do a release for CI to publish the changes to ReadTheDocs.
We 're planning a patch release soon.

**Comment by benhorsburgh** [comment]
This has now been updated and works as expected. Thanks for pointing it out
